### ISSUE TITLE
Cannot find module './lib/aws'

### ISSUE THREAD

**Issue by cibernox** [tomdale/ember-cli-deploy-elastic-beanstalk#1]
I think I've followed all the steps in `ember-cli-deploy-s3` and here. 
I've successfully provisioned a tier in aws but when it comes to deploy I get this stack trace.

```
Cannot find module './lib/aws'
Error: Cannot find module './lib/aws'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/miguelcamba/code/own/ember-power-select/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/index.js:2:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/miguelcamba/code/own/ember-power-select/node_modules/ember-cli-deploy-elastic-beanstalk/lib/elastic-beanstalk-deploy-plugin.js:8:25)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
```

In case it makes a difference, the app I'm trying to deploy is actually the dummy app in an addon, so everything is open source in case it helps.

Probably I'm missing something obvious, aws is confusing as hell for me.

**Comment by tomdale** [comment]
@cibernox Based on the stack trace, it seems like the missing module is coming from within the aws-sdk itself? I wonder if there was a bad publish of the npm package?

**Comment by cibernox** [comment]
Unsure, I haven't tried since. Either way this is ~18 months old. Let's close it

**Comment by tomdale** [comment]
👍
