### ISSUE TITLE
ember eb:provision Unable to download from S3 location (301)

### ISSUE THREAD

**Issue by xn** [tomdale/ember-cli-deploy-elastic-beanstalk#5]
I'm getting a 301 in trying to provision.
Error:

```
Creating Elastic Beanstalk application version
Unable to download from S3 location (Bucket: fastboot-aws  Key: fastboot-aws-latest.zip). Reason: Moved Permanently
InvalidParameterCombination: Unable to download from S3 location (Bucket: fastboot-aws  Key: fastboot-aws-latest.zip). Reason: Moved Permanently
    at Request.extractError (/Users/xn/sites/thing/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/xn/sites/thing/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/xn/sites/thing/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xn/sites/thing/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xn/sites/thing/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/Users/xn/sites/thing/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/xn/sites/thing/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/xn/sites/thing/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xn/sites/thing/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xn/sites/thing/node_modules/aws-sdk/lib/request.js:38:9)
```

deploy.js

```
    ENV['elastic-beanstalk'] = {
      bucket: process.env.STAGING_BUCKET
    }
    ENV.s3 = {
      accessKeyId: process.env.AWS_KEY,
      secretAccessKey: process.env.AWS_SECRET,
      bucket: process.env.STAGING_BUCKET,
      region: process.env.STAGING_REGION
    }
```

Maybe the s3 url is mangled?

**Comment by xn** [comment]
This was because there were multiple dependency issues. At some point I'll create a PR with some solid documentation.
