### ISSUE TITLE
MissingRequiredParameter: Missing required key 'Key' in params

### ISSUE THREAD

**Issue by kieranhall** [tomdale/ember-cli-deploy-elastic-beanstalk#8]
Complete stack trace:

```
+- upload
|  |
|  +- elastic-beanstalk
- uploading tmp/deploy-dist-1d0832b056db7adf518bca06279d56ee.zip to ember-deployment-fastboot-test
|
+- didFail
MissingRequiredParameter: Missing required key 'Key' in params
    at ParamValidator.fail (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/event_listeners.js:109:42)
    at Request.callListeners (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/kieranhall/workspace/mindcurv/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/kieranhall/workspace/aws-deployment-test/node_modules/ember-cli-deploy-elastic-beanstalk/node_modules/aws-sdk/lib/config.js:308:7)
```

Prior to getting this error, my config object looked like:

```
'elastic-beanstalk': {
  bucket: 'ember-deployment-fastboot-test'
}
```

After some tinkering and help from Michael Klein, we determined that the config needs to have a _key_ key defining like so:

```
'elastic-beanstalk': {
  bucket: 'ember-deployment-fastboot-test',
  key: 'fastboot-dist.json' // inline with fastboot-aws server requirements
}
```

After this change, the deployment works, and I see my dist-***.zip in my bucket, plus the key configuration creates a file by the same name, with the expected mapping to be picked up by EB.

Perhaps the AWS CLI API changed?  I am working with [this version](https://pypi.python.org/pypi/awscli/1.11.21) on my machine.

I'll prepare a PR for the documentation change.

**Comment by baumann** [comment]
I'm having the same issue. Were you able to overcome it by now?
